### ISSUE TITLE
disable amd gpu

### ISSUE THREAD

**Issue by akshay7802** [anandrajaram21/hackintosh#3]
how did you managed to disable amd gpu.
I am only getting 2 hours of battery life while I was using clover the battery life was around 4 hours is there any way to mange power?

**Comment by anandrajaram21** [comment]
I'm not too sure about that, I always used my laptop plugged in

**Comment by anandrajaram21** [comment]
https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html
