### ISSUE TITLE
DRM CONTENT

### ISSUE THREAD

**Issue by sai5567** [anandrajaram21/hackintosh#4]
Hey did u manage to play drm content on safari?

**Comment by tvserial** [comment]
How can i Join the init segment with all other segments then decrypt using ??

**Comment by anandrajaram21** [comment]
> Hey did u manage to play drm content on safari?

https://dortania.github.io/OpenCore-Post-Install/universal/drm.html. Please check this out. I didnt fix DRM content, but this page should help you fix it

**Comment by anandrajaram21** [comment]
> How can i Join the init segment with all other segments then decrypt using ??

What ?????
