### ISSUE TITLE
label:question Question: sleep not working

### ISSUE THREAD

**Issue by nvantan2** [anandrajaram21/hackintosh#5]

**Comment by nvantan2** [comment]
can you help me? thank's very much.

**Comment by anandrajaram21** [comment]
I have not fixed sleep as it was not a priority for me. You can check this page out if you want to fix it on your own.  
[Fixing Sleep](https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html).  
As mentioned in the README, this repo must only be used as a reference and not as a drop in replacement for your EFI.
