### ISSUE TITLE
Detailed Process

### ISSUE THREAD

**Issue by thelastbackspace** [anandrajaram21/hackintosh#7]
Hi,

I really want to install it on my inspiron 5567. Can you please share the detailed process?
I will be really thankful.

**Comment by anandrajaram21** [comment]
Unfortunately, I don't have enough time on my hands to make a guide of some sort, but I just followed the official OpenCore documentation over at [https://dortania.github.io](https://dortania.github.io). It is pretty easy to follow.

**Comment by pedropneves** [comment]
This is my current UFEI folder, I'm using in my Dell Inspiron 5567 with BigSur 11.5.2
I Hope this files can help you.

https://drive.google.com/drive/folders/1o4QMPICsRcJtvh-h2AVkXMptO8iw9aEV?usp=sharing

**Comment by thelastbackspace** [comment]
Thanks for the help buddy, but the folder that you shared is empty
Can you upload the folder to the same link?
Thanks Already

**Comment by thelastbackspace** [comment]
> This is my current UFEI folder, I'm using in my Dell Inspiron 5567 with BigSur 11.5.2
> I Hope this files can help you.
> 
> https://drive.google.com/drive/folders/1o4QMPICsRcJtvh-h2AVkXMptO8iw9aEV?usp=sharing

Thanks for the help buddy, but the folder that you shared is empty
Can you upload the folder to the same link?
Thanks Already
@pedropneves

**Comment by pedropneves** [comment]
Hi, I don't now why, but google block access at files.

Try with this link
https://mega.nz/file/c8wECb7B#JCVu4iTtmN550tnpj12v7Na1YGJJZ0wC7OGnkisSTMY

**Comment by Sai55567** [comment]
> Hi, I don't now why, but google block access at files.
> 
> Try with this link https://mega.nz/file/c8wECb7B#JCVu4iTtmN550tnpj12v7Na1YGJJZ0wC7OGnkisSTMY

hi bro I tried your EFI everything is fine except that I can't use my wireless mouse 
do u have any fixes for that??

also I was wondering how is your laptop battery life using this EFI

does sleep functionality works well?? I didn't checkit myself as my wireless mouse is not working with this EFI I didn't feel comfortable with that so I reverted back to my old one

bro one last question did you updated to MONTEREY  I tried to update my EFI to OC 0.7.5 but unable to boot as  there are lot of kernel panics in my EFI 

if you succeed in MONTEREY please do share your EFI it will be very helpful

Lastly thank you for sharing the EFI
